# HelloWorld Dockerfile by GeerlingGuy
# https://github.com/geerlingguy/ansible-for-devops/blob/master/docker/test/Dockerfile
# Build an example Docker container image.
FROM busybox
LABEL maintainer="Jeff Geerling"

# Run a command when the container starts:
CMD ["/bin/true"]
   # bin/true  returns STATUS Exited (0)
   # bin/false returns STATUS Exited (1)